---
post_url: /t/tds-official-project1-discrepencies/171141/225
---
[![1000004190](https://europe1.discourse-cdn.com/flex013/uploads/iitm/optimized/3X/6/a/6a204d9c51d90a584e4e56d593b24821129e056e_2_519x500.png)

10000041901193×1149 136 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/6/a/6a204d9c51d90a584e4e56d593b24821129e056e.png "1000004190")

  
Here it is with the task, however the error doesn’t seem to be related to the task itself based on the returned message in the JSON. It seems to be something wrong with the OpenAI API key. From the reading I did, it seems that the key was perhaps not set properly during evaluation? Not completely sure but please look into it.