{"id": 616862, "name": "Carlton D'Silva", "username": "carlton", "avatar_template": "/user_avatar/discourse.onlinedegree.iitm.ac.in/carlton/{size}/56317_2.png", "created_at": "2025-04-08T06:29:24.100Z", "cooked": "<p>There is <strong>clearly</strong> <em>some difference</em> between both the applications. That is up to you to figure out. I can only tell whats wrong with yours. After building it and trying to run it this is the error we get. It fails to run as a result and we cannot evaluate it.</p>\n<pre><code class=\"lang-auto\">Traceback (most recent call last):\n  File \"/usr/local/bin/uvicorn\", line 8, in &lt;module&gt;\n    sys.exit(main())\n             ^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/click/core.py\", line 1161, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/click/core.py\", line 1082, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/click/core.py\", line 1443, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/click/core.py\", line 788, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/main.py\", line 412, in main\n    run(\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/main.py\", line 579, in run\n    server.run()\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/server.py\", line 66, in run\n    return asyncio.run(self.serve(sockets=sockets))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/asyncio/runners.py\", line 195, in run\n    return runner.run(main)\n           ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/asyncio/base_events.py\", line 691, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/server.py\", line 70, in serve\n    await self._serve(sockets)\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/server.py\", line 77, in _serve\n    config.load()\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/config.py\", line 435, in load\n    self.loaded_app = import_from_string(self.app)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/importer.py\", line 22, in import_from_string\n    raise exc from None\n  File \"/usr/local/lib/python3.12/site-packages/uvicorn/importer.py\", line 19, in import_from_string\n    module = importlib.import_module(module_str)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1387, in _gcd_import\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1360, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1331, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 935, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap_external&gt;\", line 999, in exec_module\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 488, in _call_with_frames_removed\n  File \"/app/app.py\", line 23, in &lt;module&gt;\n    from tasksB import *\n  File \"/app/tasksB.py\", line 83, in &lt;module&gt;\n    from flask import Flask, request, jsonify\nModuleNotFoundError: No module named 'flask'\n</code></pre>", "post_number": 436, "post_type": 1, "posts_count": 467, "updated_at": "2025-04-08T06:29:24.100Z", "reply_count": 0, "reply_to_post_number": 430, "quote_count": 0, "incoming_link_count": 0, "reads": 60, "readers_count": 59, "score": 11.8, "yours": false, "topic_id": 171141, "topic_slug": "tds-official-project1-discrepencies", "display_username": "Carlton D'Silva", "primary_group_name": "ds-students", "flair_name": "ds-students", "flair_url": null, "flair_bg_color": "", "flair_color": "", "flair_group_id": 294, "badges_granted": [], "version": 1, "can_edit": false, "can_delete": false, "can_recover": false, "can_see_hidden_post": false, "can_wiki": false, "read": false, "user_title": "Regular", "title_is_group": false, "reply_to_user": {"id": 17940, "username": "23f1000879", "name": "Bharat Choudhary", "avatar_template": "/user_avatar/discourse.onlinedegree.iitm.ac.in/23f1000879/{size}/66976_2.png"}, "bookmarked": false, "actions_summary": [{"id": 2, "can_act": true}, {"id": 6, "can_act": true}, {"id": 3, "can_act": true}, {"id": 4, "can_act": true}, {"id": 8, "can_act": true}, {"id": 10, "can_act": true}, {"id": 7, "can_act": true}], "moderator": false, "admin": false, "staff": false, "group_moderator": true, "user_id": 16094, "hidden": false, "trust_level": 3, "deleted_at": null, "user_deleted": false, "edit_reason": null, "can_view_edit_history": true, "wiki": false, "post_url": "/t/tds-official-project1-discrepencies/171141/436", "user_cakedate": "2023-01-25", "reactions": [], "current_user_reaction": null, "reaction_users_count": 0, "current_user_used_main_reaction": false, "can_accept_answer": false, "can_unaccept_answer": false, "accepted_answer": false, "topic_accepted_answer": null}