---
post_url: /t/tds-official-project1-discrepencies/171141/61
---
![](https://dub1.discourse-cdn.com/flex013/user_avatar/discourse.onlinedegree.iitm.ac.in/rohit_b_lakshmanan/48/67205_2.png) ROHIT\_B\_LAKSHMANAN:

> This is the id of the docker image that was evaluated: 468630ef32b8

We evaluated you on correct file

[![image](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/d/7/d73b7915b1fb24bc215068e0695616f82f122f96.png)

image1757×250 24.9 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/d/7/d73b7915b1fb24bc215068e0695616f82f122f96.png "image")

![](https://dub1.discourse-cdn.com/flex013/user_avatar/discourse.onlinedegree.iitm.ac.in/rohit_b_lakshmanan/48/67205_2.png) ROHIT\_B\_LAKSHMANAN:

> what is the reason for this?  
> It was running properly before, please help.

Try running docker container after pulling, check if evaluate.py is able to do it’s job.

If you feel there is some issues from our side, we have provided with scirpts we used. You can create a pull request to [Jivraj-18/tds-jan25-project1](https://github.com/Jivraj-18/tds-jan25-project1)