---
post_url: https://discourse.onlinedegree.iitm.ac.in/t/tds-official-project1-discrepencies/171141/349
---
[@carlton](/u/carlton) and [@Jivraj](/u/jivraj) , for Task A i had tested before and all the test cases passed, but all my A tasks has failed with 0, In the evaluation logs, i could see that all task A tests failed due to datagen.py not available.

Could you rerun the test ?