---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/236
---
[@Jivraj](/u/jivraj) [@carlton](/u/carlton) sir please help

When I am downloading the data folder after processing datagen.py , it is trying to download in root folder and it is facing permission error . how can we overcome this ?  
needs sudo permission all the time…  

[![image](https://europe1.discourse-cdn.com/flex013/uploads/iitm/optimized/3X/5/2/529a3326ad0a3a4a60a7c95b080336814e487f6c_2_690x62.png)

image1368×124 19.9 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/5/2/529a3326ad0a3a4a60a7c95b080336814e487f6c.png "image")