---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/374
---
it usually happens in some GNU/Linux OS. since you are using some distribution based on Debian namely Ubuntu or whatever try doing sudo apt install python-packagename (replace package name with fastapi for fastapi)  
then it works. It usually happens due to manual intervention with pip3 the user might break some system dependencies which require some python3 package. No need to worry about it.  
Another Fix: try using a virtual environment which is highly suggested since there is no chance for you to interfere with the system packages.  
create a venv using python3 -m venv name\_of\_venv  
add this line to your .bashrc in ~ folder as source /path/to/your/venv/location  
and run source .bashrc. This time no error occurs as you do everything in your virtual environment you can install anything python3 package using pip3 install package name.  
It even happened for me

[![Screenshot_20250215_143357](https://europe1.discourse-cdn.com/flex013/uploads/iitm/optimized/3X/1/5/15e33e0ab5319a089a3cf734a66b3318dc7d08ac_2_690x181.png)

Screenshot\_20250215\_1433573841Ã—1009 237 KB](https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/1/5/15e33e0ab5319a089a3cf734a66b3318dc7d08ac.png "Screenshot_20250215_143357")