---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/517
---
uv run <https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py>  
Installed 13 packages in 543ms  
Traceback (most recent call last):  
File “/tmp/evaluateF6zgG9.py”, line 20, in   
from datagen import (  
…<9 lines>…  
)  
ModuleNotFoundError: No module named ‘datagen’

I am getting this error when I try to run evaluate.py

when I run the evaluate.py by having datagen.py in same folder , it is running perfectly. But my doubt is only after task a1 runs the datagen.py will be downloaded into the /data folder right ?

[@carlton](/u/carlton) [@Saransh\_Saini](/u/saransh_saini) [@Jivraj](/u/jivraj)  
Kindly help me with this issue