---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/538
---
I am getting this error while running evaluate.py on task A9

```
HTTP Request: POST https://aiproxy.sanand.workers.dev/openai/v1/embeddings "HTTP/1.1 401 Unauthorized"

ðŸ”´ A9 failed: 'data'

```

There were no authentication issues till yesterday.

please guide [@carlton](/u/carlton) [@Jivraj](/u/jivraj) [@Saransh\_Saini](/u/saransh_saini)